name: Build on main

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Read semantic version from pubspec.yaml
        id: ver
        run: |
          SEMVER=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
          echo "semver=$SEMVER" >> $GITHUB_OUTPUT

      - name: Flutter pub get
        run: flutter pub get

      # Android
      - name: Build Android AppBundle ğŸ› ï¸
        run: |
          flutter build appbundle \
            --build-name "${{ steps.ver.outputs.semver }}" \
            --build-number "${{ github.run_number }}"

      - name: Upload Android AppBundle â¬†ï¸
        uses: actions/upload-artifact@v4
        with:
          name: trulybudget-aab-${{ steps.ver.outputs.semver }}+${{ github.run_number }}
          path: build/app/outputs/bundle/release/app-release.aab

      # APK
      - name: Build Android debug APK ğŸ› ï¸
        run: |
          flutter build apk \
            --debug \
            --build-name "${{ steps.ver.outputs.semver }}" \
            --build-number "${{ github.run_number }}"

      - name: Upload debug APK â¬†ï¸
        uses: actions/upload-artifact@v4
        with:
          name: trulybudget-apk-debug-${{ steps.ver.outputs.semver }}+${{ github.run_number }}
          path: build/app/outputs/flutter-apk/app-debug.apk
